// SPDX-FileCopyrightText: 2026 Yvig Bidon
// SPDX-License-Identifier: AGPL-3.0-or-later

import { PrismaClient } from '@prisma/client';
import { join } from 'node:path';
import { FILMS, OUT_DIR, REPO_ROOT, SAMPLE_PASSWORD, WORK_DIR, WORKS } from './config';
import { CAMINANDES } from './data/project-caminandes';
import { SERVICE_ACCOUNT, TEAM } from './data/team';
import type { ProjectSpec } from './data/types';
import { planProject } from './generate';
import { ensureDir, writeText } from './lib/download';
import { seedChat } from './seed/chat';
import { seedExtras } from './seed/extras';
import { SessionPool, seedMedia } from './seed/media';
import { seedProject } from './seed/project';
import { seedReview } from './seed/review';
import { seedStudio } from './seed/studio';
import { seedApiTokens, seedAudit, seedHdris, seedProjectReferences } from './seed/studio-extras';
import { seedThumbnails } from './seed/thumbnails';

/**
 * Générateur du projet de démonstration.
 *
 * Il produit un studio complet — équipe, série de trois épisodes, médias réels, historique
 * de review — à partir de sources exclusivement libres. Rien n'est commité : les fichiers
 * sont fabriqués dans `dev_data/sample-project/` et déposés dans l'instance locale.
 *
 * Usage :
 *   npm run sample                   toute la génération
 *   npm run sample -- --skip-media   structure seule (rapide)
 *   npm run sample -- --reset        efface le projet de démonstration d'abord
 */

const PROJECTS: ProjectSpec[] = [CAMINANDES];

interface Options {
  projects: string[];
  skipMedia: boolean;
  reset: boolean;
  concurrency: number;
}

function parseOptions(argv: string[]): Options {
  const get = (name: string): string | undefined =>
    argv
      .find((a) => a.startsWith(`--${name}=`))
      ?.split('=')
      .slice(1)
      .join('=');
  const wanted = get('projects')
    ?.split(',')
    .map((s) => s.trim())
    .filter(Boolean);
  return {
    projects: wanted && wanted.length > 0 ? wanted : PROJECTS.map((p) => p.slug),
    skipMedia: argv.includes('--skip-media'),
    reset: argv.includes('--reset'),
    concurrency: Number(get('concurrency') ?? 3),
  };
}

/** Crédits des sources — obligation de la licence CC BY, y compris pour une démonstration. */
async function writeAttribution(projects: ProjectSpec[]): Promise<string> {
  const works = new Set<string>(['polyHaven', 'khronos']);
  // Chaque film source déclare l'œuvre qu'il faut créditer : trois épisodes, une œuvre.
  for (const project of projects) {
    for (const key of [project.film, ...(project.episodes ?? []).map((e) => e.film)]) {
      const work = WORKS[FILMS[key]?.work ?? ''];
      if (work) works.add(work.key);
    }
  }
  const lines = [
    '# Sample project — attribution',
    '',
    'Every asset used by the ReView sample project is free to redistribute. This file lists',
    'the sources, their authors and their licences, as required by CC BY.',
    '',
    '| Work | Author | Licence | Source |',
    '| --- | --- | --- | --- |',
  ];
  for (const key of works) {
    const work = WORKS[key];
    if (!work) continue;
    // Une barre verticale dans un champ casserait la colonne : elle est échappée, sinon le
    // tableau se décale d'une case et le crédit devient illisible.
    const cell = (value: string): string => value.replace(/\|/g, '\\|');
    lines.push(
      `| ${cell(work.title)} | ${cell(work.authors)} | [${work.license}](${work.licenseUrl}) | ${work.homepage} |`,
    );
  }
  lines.push(
    '',
    '## What was derived',
    '',
    '- **Video** — shots are short excerpts cut from the masters with ffmpeg, then graded to',
    '  imitate the pipeline step they stand for (layout, blocking, lighting, comp).',
    '- **USD scenes** — asset graphs and shot layer stacks are written by this generator;',
    '  the geometry comes from Poly Haven models converted with Blender.',
    '- **Gaussian splats** — produced from Poly Haven photogrammetry scans by surface',
    '  sampling. No research-only dataset is used.',
    '- **Avatars and department badges** — generated, they depict nobody.',
    '',
    `Generated by \`backend/scripts/sample-project\`. Team names are fictional.`,
    '',
  );
  const path = join(REPO_ROOT, 'ATTRIBUTION.md');
  await writeText(path, lines.join('\n'));
  return path;
}

/** Efface les projets de démonstration (et eux seuls) avant de régénérer. */
async function reset(prisma: PrismaClient, slugs: string[]): Promise<void> {
  const studio = await prisma.studio.findFirst({ where: { slug: 'review-studio' } });
  if (!studio) return;
  for (const slug of slugs) {
    const project = await prisma.project.findFirst({ where: { studioId: studio.id, slug } });
    if (!project) continue;
    await prisma.project.delete({ where: { id: project.id } });
    console.info(`  – removed project ${slug}`);
  }
}

async function main(): Promise<void> {
  const options = parseOptions(process.argv.slice(2));
  const prisma = new PrismaClient();
  const started = Date.now();
  await ensureDir(OUT_DIR);

  const selected = PROJECTS.filter((p) => options.projects.includes(p.slug));
  if (selected.length === 0) throw new Error(`no known project among: ${options.projects.join(', ')}`);

  console.info('ReView sample project');
  console.info(`  work dir : ${WORK_DIR}`);
  console.info(`  projects : ${selected.map((p) => p.slug).join(', ')}`);
  console.info(`  media    : ${options.skipMedia ? 'skipped' : 'generated and uploaded'}`);

  if (options.reset) {
    console.info('\n• Resetting sample projects');
    await reset(
      prisma,
      selected.map((p) => p.slug),
    );
  }

  console.info('\n• Studio, team and departments');
  const studio = await seedStudio(prisma);
  console.info(`  ${studio.users.size} accounts, ${studio.departments.size} departments`);
  if (!options.skipMedia) {
    console.info(`  ${await seedHdris()} HDRIs added to the lighting library`);
  }
  console.info(`  ${await seedAudit(prisma, studio)} audit entries`);
  const tokens = await seedApiTokens(prisma, studio);
  for (const token of tokens) console.info(`  API token — ${token.label}: ${token.token}`);

  const memberDepartments = new Map([...TEAM, SERVICE_ACCOUNT].map((m) => [m.key, m.departments]));
  const pool = new SessionPool('ada.vermeer@sample.review');

  for (const spec of selected) {
    console.info(`\n• ${spec.name}`);
    const plan = planProject(spec, memberDepartments);
    const seeded = await seedProject(prisma, studio, plan);
    console.info(
      `  ${seeded.sequences.size} sequences, ${seeded.shots.size} shots, ${seeded.assets.size} assets, ${seeded.versions.length} versions`,
    );

    if (!options.skipMedia) {
      const total = seeded.versions.reduce((sum, v) => sum + v.planned.media.length, 0);
      console.info(`  uploading ${total} media…`);
      const media = await seedMedia(prisma, seeded, pool, {
        concurrency: options.concurrency,
        onProgress: (done, count) => {
          if (done % 10 === 0 || done === count) process.stdout.write(`\r    ${done}/${count}   `);
        },
      });
      process.stdout.write('\n');
      console.info(`  ${media.uploaded} processed, ${media.failed} failed`);
      const review = await seedReview(prisma, studio, seeded, media.byVersion);
      console.info(`  ${review.comments} comments, ${review.decisions} decisions, ${review.markers} markers`);
      await seedThumbnails(prisma, seeded);
      const references = await seedProjectReferences(prisma, studio, seeded);
      if (references > 0) console.info(`  ${references} pinned reference images`);
    } else {
      const review = await seedReview(prisma, studio, seeded, new Map());
      console.info(`  ${review.decisions} decisions (media skipped)`);
    }

    const extras = await seedExtras(prisma, studio, seeded);
    console.info(
      `  ${extras.playlists} playlists, ${extras.shares} share links, ${extras.timelines} timelines`,
    );
  }

  console.info('\n• Team chat');
  console.info(`  ${await seedChat(prisma, studio)} messages`);

  const attribution = await writeAttribution(selected);
  console.info(`\n• Attribution written to ${attribution}`);

  console.info(`\nDone in ${Math.round((Date.now() - started) / 1000)} s.`);
  console.info(`Sign in with any of the sample accounts, password: ${SAMPLE_PASSWORD}`);
  console.info('  ada.vermeer@sample.review      admin / pipeline TD');
  console.info('  marisol.quintero@sample.review VFX supervisor');
  console.info('  elodie.fournier@sample.review  animator');
  console.info('  lucas.meyer@client.sample      client');
  await prisma.$disconnect();
}

void main()
  .then(() => {
    // Sortie explicite : le client S3 et les connexions HTTP gardent des sockets ouvertes
    // (keep-alive), et le processus restait vivant plusieurs minutes après avoir terminé —
    // une génération qui « ne finit pas » alors que tout est écrit.
    process.exit(0);
  })
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
